"use client";

import React, { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createStudent } from "@/app/actions/students/Student-services";
import { fetchClasses } from "@/app/actions/classes/class-services";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function AddStudentPage() {
  const router = useRouter();

  const inputClasses =
    "form-input border rounded-md p-2 w-full bg-white dark:bg-gray-900 " +
    "border-neutral-300 dark:border-neutral-700 text-sm " +
    "focus:ring-2 focus:ring-blue-500 focus:border-blue-600 transition";

  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isDragOver, setIsDragOver] = useState(false);
  const [formData, setFormData] = useState({
    first_name: "",
    last_name: "",
    father_name: "",
    grand_father_name: "",
    dob: "",
    age: "",
    gender: "male",
    address: "",
    primary_mobile: "",
    secondary_mobile: "",
    email: "",
    status: "pending",
    country: "",
    current_province: "",
    main_province: "",
    class_id: "",
    image: null as File | null,
  });

  const [classes, setClasses] = useState<any[]>([]);
  const [loadingClasses, setLoadingClasses] = useState(true);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    const loadClasses = async () => {
      try {
        const res = await fetchClasses();
        setClasses(res);
      } catch (error: any) {
        toast.error(error.message || "Failed to load classes");
      } finally {
        setLoadingClasses(false);
      }
    };

    loadClasses();
  }, []);

  const handleChange = (
    e: React.ChangeEvent<
      HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement
    >
  ) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    processFile(file);
  };

  const processFile = (file: File) => {
    // Validate file type
    if (!file.type.startsWith('image/')) {
      toast.error('Please select a valid image file');
      return;
    }

    // Validate file size (5MB limit)
    if (file.size > 5 * 1024 * 1024) {
      toast.error('File size must be less than 5MB');
      return;
    }

    const previewURL = URL.createObjectURL(file);
    setImagePreview(previewURL);
    setFormData((prev) => ({ ...prev, image: file }));
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);

    const files = e.dataTransfer.files;
    if (files.length > 0) {
      processFile(files[0]);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      // Convert form data to Student object format
      const studentData = {
        id: "", // Will be generated by the API
        first_name: formData.first_name,
        last_name: formData.last_name,
        father_name: formData.father_name,
        grand_father_name: formData.grand_father_name,
        dob: formData.dob,
        age: formData.age,
        gender: formData.gender as "male" | "female",
        address: formData.address,
        primary_mobile: formData.primary_mobile,
        secondary_mobile: formData.secondary_mobile,
        email: formData.email,
        status: formData.status as "active" | "inactive" | "pending" | "blocked" | "deleted",
        country: formData.country,
        current_province: formData.current_province,
        main_province: formData.main_province,
        class_id: formData.class_id,
        image: formData.image || "", // File or empty string
      };

      await createStudent(studentData as any);
      toast.success("Student created successfully!");
      router.push("/students");
    } catch (error: any) {
      toast.error(error.message || "Failed to create student");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl font-semibold">Add New Student</CardTitle>
        </CardHeader>
        <CardContent>


          <form onSubmit={handleSubmit} className="space-y-8">
            {/* Section 1: Photo and Basic Information */}
            <div className="rounded-2xl border border-border bg-card p-8 shadow-sm transition-all duration-200 hover:shadow-md">
              <div className="grid grid-cols-1 gap-8 lg:grid-cols-2">

                {/* Photo Upload Section */}
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary"></div>
                    <h3 className="text-xl font-semibold text-foreground">Student Photo</h3>
                  </div>

                  {/* Hidden File Input */}
                  <input
                    type="file"
                    name="image"
                    id="imageInput"
                    onChange={handleFileChange}
                    accept="image/*"
                    className="hidden"
                    aria-label="Upload student photo"
                  />

                  {/* Enhanced Photo Upload Area */}
                  <div className="relative">
                    <div
                      onClick={() => document.getElementById("imageInput")?.click()}
                      onDragOver={handleDragOver}
                      onDragLeave={handleDragLeave}
                      onDrop={handleDrop}
                      className={`group relative flex h-80 w-full cursor-pointer flex-col items-center justify-center overflow-hidden
                               rounded-xl border-2 border-dashed transition-all duration-200
                               ${isDragOver
                                 ? 'border-primary bg-primary/10 scale-[1.02]'
                                 : 'border-muted-foreground/25 bg-muted/30 hover:border-primary/50 hover:bg-primary/5'
                               }
                               focus-within:border-primary focus-within:ring-2 focus-within:ring-primary/20`}
                      role="button"
                      tabIndex={0}
                      onKeyDown={(e) => {
                        if (e.key === 'Enter' || e.key === ' ') {
                          e.preventDefault();
                          document.getElementById("imageInput")?.click();
                        }
                      }}
                    >
                      {imagePreview ? (
                        <div className="relative h-full w-full">
                          <img
                            src={imagePreview}
                            alt="Student photo preview"
                            className="h-full w-full object-cover"
                          />
                          <div className="absolute inset-0 bg-black/40 opacity-0 transition-opacity group-hover:opacity-100">
                            <div className="flex h-full items-center justify-center">
                              <div className="rounded-lg bg-white/90 px-4 py-2 text-sm font-medium text-gray-900 shadow-lg">
                                Click to change photo
                              </div>
                            </div>
                          </div>
                        </div>
                      ) : (
                        <div className="flex flex-col items-center gap-4 text-center">
                          <div className="rounded-full bg-primary/10 p-4 transition-colors group-hover:bg-primary/20">
                            <svg
                              className="h-8 w-8 text-primary"
                              fill="none"
                              stroke="currentColor"
                              viewBox="0 0 24 24"
                            >
                              <path
                                strokeLinecap="round"
                                strokeLinejoin="round"
                                strokeWidth={2}
                                d="M16 21v-2a4 4 0 00-4-4H6a4 4 0 00-4 4v2m16-6V9a4 4 0 00-4-4h-2m-4 0V3a2 2 0 114 0v2M9 9h6m-6 4h6"
                              />
                            </svg>
                          </div>
                          <div className="space-y-1">
                            <p className="text-sm font-medium text-foreground">Upload Student Photo</p>
                            <p className="text-xs text-muted-foreground">
                              Click to browse or drag and drop
                            </p>
                            <p className="text-xs text-muted-foreground">PNG, JPG up to 5MB</p>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>

                {/* Basic Information Section */}
                <div className="space-y-6">
                  <div className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary"></div>
                    <h3 className="text-xl font-semibold text-foreground">Basic Information</h3>
                  </div>

                  <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
                    {/* First Name */}
                    <div className="space-y-2">
                      <label htmlFor="first_name" className="text-sm font-medium text-foreground">
                        First Name <span className="text-destructive">*</span>
                      </label>
                      <input
                        type="text"
                        id="first_name"
                        name="first_name"
                        value={formData.first_name}
                        onChange={handleChange}
                        required
                        className={inputClasses}
                        placeholder="Enter first name"
                      />
                    </div>

                    {/* Last Name */}
                    <div className="space-y-2">
                      <label htmlFor="last_name" className="text-sm font-medium text-foreground">
                        Last Name <span className="text-destructive">*</span>
                      </label>
                      <input
                        type="text"
                        id="last_name"
                        name="last_name"
                        value={formData.last_name}
                        onChange={handleChange}
                        required
                        className={inputClasses}
                        placeholder="Enter last name"
                      />
                    </div>

                    {/* Father Name */}
                    <div className="space-y-2">
                      <label htmlFor="father_name" className="text-sm font-medium text-foreground">
                        Father Name
                      </label>
                      <input
                        type="text"
                        id="father_name"
                        name="father_name"
                        value={formData.father_name}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="Enter father's name"
                      />
                    </div>

                    {/* Grandfather Name */}
                    <div className="space-y-2">
                      <label htmlFor="grand_father_name" className="text-sm font-medium text-foreground">
                        Grandfather Name
                      </label>
                      <input
                        type="text"
                        id="grand_father_name"
                        name="grand_father_name"
                        value={formData.grand_father_name}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="Enter grandfather's name"
                      />
                    </div>
                    <div>
                      <label htmlFor="age" className="text-sm font-medium text-foreground">
                      Age
                      </label>
                      <input
                        type="text"
                        id="age"
                        name="age"
                        value={formData.age}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="Enter your age"
                      />
                    </div>
                      <div>
                      <label htmlFor="class_id" className="text-sm font-medium text-foreground">
                        Class <span className="text-destructive">*</span>
                      </label>
                      <select
                        id="class_id"
                        name="class_id"
                        value={formData.class_id}
                        onChange={handleChange}
                        required
                        disabled={loadingClasses}
                        className={inputClasses}
                      >
                        <option value="">
                          {loadingClasses ? "Loading classes..." : "Select a class"}
                        </option>
                        {!loadingClasses &&
                          classes.map((cls) => (
                            <option key={cls.id} value={cls.id}>
                              {cls.class_name || cls.name}
                            </option>
                          ))}
                      </select>
                      </div>

                 

                    {/* Class Selection - Full Width */}
                    <div className="space-y-2 sm:col-span-2">
                 
                    </div>
                  </div>
                </div>
              </div>
            </div>


            {/* Section 2: Personal Information, Contact & Location */}
            <div className="rounded-2xl border border-border bg-card p-8 shadow-sm transition-all duration-200 hover:shadow-md">
              <div className="space-y-8">

                {/* Personal Information */}
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary"></div>
                    <h3 className="text-xl font-semibold text-foreground">Personal Information</h3>
                  </div>

                  <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                    <div className="space-y-2">
                      <label htmlFor="dob" className="text-sm font-medium text-foreground">
                        Date of Birth <span className="text-destructive">*</span>
                      </label>
                      <input
                        type="date"
                        id="dob"
                        name="dob"
                        value={formData.dob}
                        onChange={handleChange}
                        required
                        className={inputClasses}
                      />
                    </div>

                    <div className="space-y-2">
                      <label htmlFor="gender" className="text-sm font-medium text-foreground">
                        Gender <span className="text-destructive">*</span>
                      </label>
                      <select
                        id="gender"
                        name="gender"
                        value={formData.gender}
                        onChange={handleChange}
                        required
                        className={inputClasses}
                      >
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="other">Other</option>
                      </select>
                    </div>

                    <div className="space-y-2">
                      <label htmlFor="status" className="text-sm font-medium text-foreground">
                        Status <span className="text-destructive">*</span>
                      </label>
                      <select
                        id="status"
                        name="status"
                        value={formData.status}
                        onChange={handleChange}
                        required
                        className={inputClasses}
                      >
                        <option value="active">Active</option>
                        <option value="inactive">Inactive</option>
                        <option value="pending">Pending</option>
                        <option value="blocked">Blocked</option>
                        <option value="deleted">Deleted</option>
                      </select>
                    </div>
                  </div>
                </div>

                {/* Contact Information */}
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary"></div>
                    <h3 className="text-xl font-semibold text-foreground">Contact Information</h3>
                  </div>

                  <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                    <div className="space-y-2">
                      <label htmlFor="primary_mobile" className="text-sm font-medium text-foreground">
                        Primary Mobile <span className="text-destructive">*</span>
                      </label>
                      <input
                        type="tel"
                        id="primary_mobile"
                        name="primary_mobile"
                        value={formData.primary_mobile}
                        onChange={handleChange}
                        required
                        className={inputClasses}
                        placeholder="+1 (555) 000-0000"
                      />
                    </div>

                    <div className="space-y-2">
                      <label htmlFor="secondary_mobile" className="text-sm font-medium text-foreground">
                        Secondary Mobile
                      </label>
                      <input
                        type="tel"
                        id="secondary_mobile"
                        name="secondary_mobile"
                        value={formData.secondary_mobile}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="+1 (555) 000-0000"
                      />
                    </div>

                    <div className="space-y-2">
                      <label htmlFor="email" className="text-sm font-medium text-foreground">
                        Email Address
                      </label>
                      <input
                        type="email"
                        id="email"
                        name="email"
                        value={formData.email}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="student@example.com"
                      />
                    </div>
                  </div>
                </div>

                {/* Location Information */}
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary"></div>
                    <h3 className="text-xl font-semibold text-foreground">Location Information</h3>
                  </div>

                  <div className="grid grid-cols-1 gap-6 md:grid-cols-3">
                    <div className="space-y-2">
                      <label htmlFor="country" className="text-sm font-medium text-foreground">
                        Country
                      </label>
                      <input
                        type="text"
                        id="country"
                        name="country"
                        value={formData.country}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="Enter country"
                      />
                    </div>

                    <div className="space-y-2">
                      <label htmlFor="current_province" className="text-sm font-medium text-foreground">
                        Current Province
                      </label>
                      <input
                        type="text"
                        id="current_province"
                        name="current_province"
                        value={formData.current_province}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="Enter current province"
                      />
                    </div>

                    <div className="space-y-2">
                      <label htmlFor="main_province" className="text-sm font-medium text-foreground">
                        Main Province
                      </label>
                      <input
                        type="text"
                        id="main_province"
                        name="main_province"
                        value={formData.main_province}
                        onChange={handleChange}
                        className={inputClasses}
                        placeholder="Enter main province"
                      />
                    </div>
                  </div>
                </div>

                {/* Address */}
                <div className="space-y-4">
                  <div className="flex items-center gap-2">
                    <div className="h-2 w-2 rounded-full bg-primary"></div>
                    <h3 className="text-xl font-semibold text-foreground">Address</h3>
                  </div>

                  <div className="space-y-2">
                    <label htmlFor="address" className="text-sm font-medium text-foreground">
                      Full Address
                    </label>
                    <textarea
                      id="address"
                      name="address"
                      value={formData.address}
                      onChange={handleChange}
                      rows={4}
                      className={`${inputClasses} resize-none`}
                      placeholder="Enter complete address including street, city, postal code..."
                    />
                  </div>
                </div>
              </div>
            </div>

            {/* Form Actions */}
            <div className="flex flex-col justify-end gap-4 rounded-2xl border border-border bg-card p-6 shadow-sm sm:flex-row">
              <Button
                type="button"
                variant="outline"
                className="order-2 sm:order-1"
                onClick={() => router.back()}
              >
                Cancel
              </Button>
              <Button
                type="submit"
                className="order-1 sm:order-2"
                disabled={loading}
              >
                {loading ? (
                  <>
                    <svg className="mr-2 h-4 w-4 animate-spin" viewBox="0 0 24 24">
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                        fill="none"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      />
                    </svg>
                    Saving...
                  </>
                ) : (
                  <>
                    <svg className="mr-2 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                    Add Student
                  </>
                )}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

